In [1]:
import numpy as np

In [2]:
vector_np = np.array([1, 2])
vector_np

array([1, 2])

In [3]:
vector1_zeros = np.zeros((10,))
print(vector1_zeros)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [4]:
vector2_zeros = np.zeros((1, 10))
print(vector2_zeros)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [5]:
vector1_ones = np.ones(10,)
print(vector1_ones)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [9]:
vector2_ones = np.ones((1,5))
print(vector2_ones)

[[1. 1. 1. 1. 1.]]


In [10]:
vector1_v_zeros = np.zeros((5,1))
print(vector1_v_zeros)

[[0.]
 [0.]
 [0.]
 [0.]
 [0.]]


In [12]:
vector2_v_ones = np.ones((5,1))
print(vector2_v_ones)

[[1.]
 [1.]
 [1.]
 [1.]
 [1.]]


In [13]:
m1_square = np.array([[11, 12, 13], [21, 22, 23], [31, 32,33]])
print(m1_square)

[[11 12 13]
 [21 22 23]
 [31 32 33]]


In [14]:
m2 = [[11, 12,13], [21, 22, 23], [31, 32, 33]]
m2_square = np.array(m2)
print(m2_square)

[[11 12 13]
 [21 22 23]
 [31 32 33]]


In [15]:
m3_square = np.matrix('11 12 13; 21 22 23; 31 32 33')
print(m3_square)

[[11 12 13]
 [21 22 23]
 [31 32 33]]


In [17]:
m1 = [[1, 0, 0], [0, 2, 0], [0, 0, 3]]
m1_diag = np.matrix(m1)
print(m1_diag)

[[1 0 0]
 [0 2 0]
 [0 0 3]]


In [18]:
m2_diag = np.diag(m1)
print(m2_diag)

[1 2 3]


In [19]:
m3_diag = np.diag(np.diag(m1))
print(m3_diag)

[[1 0 0]
 [0 2 0]
 [0 0 3]]


In [21]:
m1_e = [[1, 0, 0], [0, 1, 0], [0, 0, 1]]
m1_e_array = np.matrix(m1_e)
print(m1_e_array)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [22]:
m_eye = np.eye(5)
print(m_eye)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [24]:
m_ident = np.identity(5)
print(m_ident)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [26]:
m1_mx = np.matrix('1 2 3; 4 5 6')
print(m1_mx)

[[1 2 3]
 [4 5 6]]


In [27]:
m1_var = np.zeros((5, 4))
print(m1_var)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [28]:
A = np.matrix('1 2 3; 4 5 6')
A_t = A.transpose()
print(A_t)

[[1 4]
 [2 5]
 [3 6]]


In [29]:
print(A.T)

[[1 4]
 [2 5]
 [3 6]]


In [30]:
Aa = A.T.T
print(Aa)

[[1 2 3]
 [4 5 6]]


In [31]:
B = np.matrix('6 5 4; 3 2 1')
C = (A + B).T
D = A.T + B.T
print(C)
print(D)

[[7 7]
 [7 7]
 [7 7]]
[[7 7]
 [7 7]
 [7 7]]


In [32]:
k = 15
E = (k * A).T
F = k * (A.T)
print(E)
print(F)

[[15 60]
 [30 75]
 [45 90]]
[[15 60]
 [30 75]
 [45 90]]


In [37]:
I = np.matrix('1 2; 9 0')
I_det = np.linalg.det(I)
I_T_det = np.linalg.det(I.T)
print(format(I_det, '.9g'))
print(format(I_T_det, '.9g'))

-18
-18


In [38]:
G = 5 * A
print(G)

[[ 5 10 15]
 [20 25 30]]


In [39]:
J = np.matrix('1 2; 3 4')
I = np.matrix('0 0; 0 0')
K = 0 * J
L = I
print(K)
print(L)

[[0 0]
 [0 0]]
[[0 0]
 [0 0]]


In [43]:
J = np.matrix('1 2; 3 4')
k = 5
l = 6
M = (k + l) * J
N = k * J + l * J
print(M)
print(N)

[[11 22]
 [33 44]]
[[11 22]
 [33 44]]


In [44]:
O = A + B
P = B + A
print(P)
print(O)

[[7 7 7]
 [7 7 7]]
[[7 7 7]
 [7 7 7]]


In [45]:
Q = A + (-1)*A
print(Q)

[[0 0 0]
 [0 0 0]]


In [46]:
B_t = B.T
R = A * B_t
print(R)

[[28 10]
 [73 28]]


In [47]:
A = np.matrix('1, 2, 3; 1, 2, 3')
B = np.matrix('5, 6; 6, 5; 5, 6')
C = A.dot(B)
print(C)

[[32 34]
 [32 34]]


In [48]:
D = B.dot(A)
print(C)
print(D)

[[32 34]
 [32 34]]
[[11 22 33]
 [11 22 33]
 [11 22 33]]


In [52]:
A = np.matrix('1 2 4; 5 6 8; 9 0 1')
E = np.matrix('1, 0, 0; 0, 1, 0; 0, 0, 1')
S = E.dot(A)
P = A.dot(E)
print(S)
print(P)

[[1 2 4]
 [5 6 8]
 [9 0 1]]
[[1 2 4]
 [5 6 8]
 [9 0 1]]


Определитель матрицы